# Generated by Django 5.1.3 on 2024-11-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0002_lockerlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_ping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='ping_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
